image: ubuntu:latest

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'

before_script:
    - apt-get update -q -y
    - echo "===> Installing and configuring tzdata"
    - export DEBIAN_FRONTEND=noninteractive
    - ln -fs /usr/share/zoneinfo/Pacific/Auckland /etc/localtime
    - apt-get install -y tzdata
    - dpkg-reconfigure --frontend noninteractive tzdata
    - echo "===> Installing Ansible..."
    - apt-get install -y ansible ansible-lint git python3
    - git submodule update --init
    - ansible --version
    - ansible-lint --version

stages:
    - verify
    - dry-run

verify:
    stage: verify
    script:
      - ansible-lint -v *.yml
      - ansible-playbook --inventory inventory/production --syntax-check *.yml
#    only:
#     changes: 
#        - ping.yml

execute_ping:
    stage: dry-run
    script: 
        - ansible-playbook ping.yml --inventory hosts --check
#    only:
#     changes:
#        - ping.yml