stages:
    - configure
    - dry-run

image: ubuntu:latest

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'

configure:
    stage: configure
    script:
        - apt-get update -q -y
        - echo "===> Installing and configuring tzdata"
        - export DEBIAN_FRONTEND=noninteractive
        - ln -fs /usr/share/zoneinfo/Pacific/Auckland /etc/localtime
        - apt-get install -y tzdata
        - dpkg-reconfigure --frontend noninteractive tzdata
        - echo "===> Installing Ansible..."
        - apt-get install -y ansible git openssh-server keychain python-pip sshpass openssh-client
        - echo "===> Adding hosts for convenience..."
        - echo 'localhost' > /etc/ansible/hosts
    only:
     changes: 
        - ping.yml

execute_ping:
    stage: dry-run
    script: ansible-playbook ping.yml --inventory hosts --limit local --check
    only:
     changes:
        - ping.yml