---
- hosts: localhost
  gather_facts: false
  become: true

  name: Install a private SSH key
  vars:
      source_key: id_rsa.crypt
      dest_key: ~/.ssh/id_rsa
  tasks:
      - name: Ensure .ssh directory exists.
        file:
            dest: "{{ dest_key | dirname }}"
            mode: 0700
            owner: root
            state: directory
      - name: Install ssh key
        copy:
            src: "{{ source_key }}"
            dest: "{{ dest_key }}"
            mode: 0600
            owner: root