---
- name: Add remote LogAnalyzer server to rsyslog.conf
  hosts: all:!LogAnalyzer
  become: true

  tasks:
    - name: Add extra entry of LogAnalyzer server to rsyslog.conf
      blockinfile:
          path: /etc/rsyslog.conf 
          backup: yes
          state: present
          block: |
            *.* @192.168.1.214:514
            *.* @@192.168.1.214:514
            $ActionQueueFileName queue
            $ActionQueueMaxDiskSpace 1g
            $ActionQueueSaveOnShutdown on
            $ActionQueueType LinkedList
            $ActionResumeRetryCount -1
      notify:
      - restart rsyslog

  handlers:
    - name: restart rsyslog
      service: name=rsyslog state=restarted
